// <auto-generated />
using Aura.Infrastructure.Adapters.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aura.Infrastructure.Adapters.Persistence.Migrations
{
    [DbContext(typeof(AuraDbContext))]
    [Migration("20260710110000_InitialCreateBaseline")]
    partial class InitialCreateBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Aura.Infrastructure.Adapters.Persistence.AlertRule", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("Key");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("AddedBy");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("RuleType");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Value");

                    b.HasKey("Key");

                    b.HasIndex("RuleType")
                        .HasDatabaseName("IX_AlertRules_RuleType");

                    b.ToTable("AlertRules", (string)null);
                });

            modelBuilder.Entity("Aura.Infrastructure.Adapters.Persistence.FocusStateOverride", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("UserId");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("State");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("UserId");

                    b.ToTable("FocusStateOverrides", (string)null);
                });

            modelBuilder.Entity("Aura.Infrastructure.Adapters.Persistence.InterruptionDecision", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Decision");

                    b.Property<string>("Explanation")
                        .HasColumnType("TEXT")
                        .HasColumnName("Explanation");

                    b.Property<string>("FocusState")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("FocusState");

                    b.Property<int?>("PriorityScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PriorityScore");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SourceType");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Timestamp");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Title");

                    b.Property<string>("WorkItemId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("WorkItemId");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("IX_InterruptionDecisions_Timestamp");

                    b.ToTable("InterruptionDecisions", (string)null);
                });

            modelBuilder.Entity("Aura.Infrastructure.Adapters.Persistence.MeetingAlertEntity", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("EventId");

                    b.Property<string>("Trigger")
                        .HasColumnType("TEXT")
                        .HasColumnName("Trigger");

                    b.Property<string>("LocalDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("LocalDate");

                    b.Property<bool>("HasBeenSent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("HasBeenSent");

                    b.Property<string>("JoinUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("JoinUrl");

                    b.Property<string>("StartsAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("StartsAtUtc");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Title");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("UserId");

                    b.HasKey("EventId", "Trigger", "LocalDate");

                    b.ToTable("MeetingAlerts", (string)null);
                });

            modelBuilder.Entity("Aura.Infrastructure.Adapters.Persistence.MorningSummaryEmission", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("UserId");

                    b.Property<string>("LocalDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("LocalDate");

                    b.Property<string>("EmittedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("EmittedAt");

                    b.HasKey("UserId", "LocalDate");

                    b.ToTable("MorningSummaryEmission", (string)null);
                });

            modelBuilder.Entity("Aura.Infrastructure.Adapters.Persistence.MsalTokenCacheEntry", b =>
                {
                    b.Property<string>("CacheKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("CacheKey");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("Data");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("CacheKey");

                    b.ToTable("MsalTokenCache", (string)null);
                });

            modelBuilder.Entity("Aura.Infrastructure.Adapters.Persistence.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Decision")
                        .HasColumnType("TEXT")
                        .HasColumnName("Decision");

                    b.Property<string>("DispatchedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("DispatchedAt");

                    b.Property<string>("Explanation")
                        .HasColumnType("TEXT")
                        .HasColumnName("Explanation");

                    b.Property<double>("Priority")
                        .HasColumnType("REAL")
                        .HasColumnName("Priority");

                    b.Property<string>("RuleResults")
                        .HasColumnType("TEXT")
                        .HasColumnName("RuleResults");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SourceType");

                    b.Property<string>("TargetUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("TargetUserId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Title");

                    b.Property<string>("TriggerRule")
                        .HasColumnType("TEXT")
                        .HasColumnName("TriggerRule");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("UserId");

                    b.Property<string>("WorkItemId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("WorkItemId");

                    b.HasKey("Id");

                    b.HasIndex("DispatchedAt")
                        .HasDatabaseName("IX_NotificationOutbox_Pending");

                    b.ToTable("NotificationOutbox", (string)null);
                });

            modelBuilder.Entity("Aura.Infrastructure.Adapters.Persistence.SemanticOutboxEntryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<string>("CanonicalSourceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CanonicalSourceId");

                    b.Property<int>("Collection")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Collection");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Content");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("Error");

                    b.Property<bool>("Processed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Processed");

                    b.Property<string>("ProcessedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("ProcessedAt");

                    b.HasKey("Id");

                    b.HasIndex("Processed", "CreatedAt")
                        .HasDatabaseName("IX_SemanticOutbox_Pending")
                        .HasFilter("[Processed] = 0");

                    b.ToTable("SemanticOutbox", (string)null);
                });

            modelBuilder.Entity("Aura.Infrastructure.Adapters.Persistence.WorkItemEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<string>("CapturedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CapturedAtUtc");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CorrelationId");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ExternalId");

                    b.Property<string>("FaultReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("FaultReason");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("MetadataJson");

                    b.Property<string>("OwnerUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("OwnerUserId");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Priority");

                    b.Property<int?>("PriorityScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PriorityScore");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SchemaVersion");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Source");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SourceType");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Title");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAtUtc")
                        .HasDatabaseName("IX_WorkItems_CapturedAtUtc");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkItems_ExternalId");

                    b.ToTable("WorkItems", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
